title: Baking Cakes
author: Daphne
email: daphne@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hello there! I am writing a blog about cakes because I have nothing else to do. 
  How are you? Do you know about cake preparation? 

# social links
github_username:  daphnetsolissou # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
